package com.erpnext.pos.localization

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String) {
    Spanish("es"),
    English("en");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.firstOrNull { it.code == code } ?: Spanish
        }
    }
}

data class AppStrings(
    val billing: BillingStrings,
    val customer: CustomerStrings,
    val inventory: InventoryStrings,
    val settings: SettingsStrings,
    val salesFlow: SalesFlowStrings,
    val navigation: NavigationStrings,
    val reconciliation: ReconciliationStrings,
    val common: CommonStrings
)

data class CommonStrings(
    val back: String,
    val retry: String,
    val remove: String,
    val clear: String,
    val link: String,
    val apply: String,
    val processing: String,
    val collapseSection: String,
    val expandSection: String,
    val imagePlaceholderDescription: String,
    val errorLabel: String
)

data class BillingStrings(
    val newInvoiceTitle: String,
    val emptyCartSnackbar: String,
    val returnButton: String,
    val customerSectionTitle: String,
    val cartSectionTitle: String,
    val creditTermsSectionTitle: String,
    val finalizeSale: String,
    val sourceDocumentLinked: String,
    val linkSourceDocument: String,
    val linkSourceDocumentTitle: String,
    val sourceTypeLabel: String,
    val sourceTypeQuotation: String,
    val sourceTypeSalesOrder: String,
    val sourceTypeDeliveryNote: String,
    val sourceTypeCustomer: String,
    val selectCustomerForDocuments: String,
    val filterByIdOrStatus: String,
    val noDocumentsFound: String,
    val dateLabel: String,
    val statusLabel: String,
    val unknownStatus: String,
    val searchCustomerLabel: String,
    val searchCustomerPlaceholder: String,
    val productSectionTitle: String,
    val productSearchLabel: String,
    val productSearchPlaceholder: String,
    val productCodeLabel: String,
    val productPriceLabel: String,
    val productAvailableLabel: String,
    val cartEmptyTitle: String,
    val cartItemsLabel: String,
    val quantityLabelShort: String,
    val decreaseQuantityDescription: String,
    val increaseQuantityDescription: String,
    val removeItemDescription: String,
    val totalsPaymentsTitle: String,
    val totalsDiscountsShippingTitle: String,
    val subtotalLabel: String,
    val taxesLabel: String,
    val discountLabel: String,
    val shippingLabel: String,
    val totalLabel: String,
    val paymentsTitle: String,
    val paymentsDisabledCreditSale: String,
    val paymentsEmpty: String,
    val amountLabel: String,
    val baseLabel: String,
    val rateLabel: String,
    val referenceLabel: String,
    val removePaymentLineDescription: String,
    val partialPaymentHint: String,
    val paymentModeLabel: String,
    val paymentModePlaceholder: String,
    val invoiceBaseCurrencyLabel: String,
    val referenceNumberLabel: String,
    val referenceRequiredHint: String,
    val addPayment: String,
    val removePayment: String,
    val paidBaseLabel: String,
    val balanceDueLabel: String,
    val changeLabel: String,
    val discountSectionTitle: String,
    val discountTypeCode: String,
    val discountTypePercent: String,
    val discountTypeAmount: String,
    val discountCodeLabel: String,
    val discountCodePlaceholder: String,
    val discountPercentLabel: String,
    val discountAmountLabel: String,
    val shippingSectionTitle: String,
    val deliveryChargePlaceholder: String,
    val deliveryChargeLabel: String,
    val noShippingOption: String,
    val discountHint: String,
    val creditSaleLabel: String,
    val paymentTermsLabel: String,
    val paymentTermPlaceholder: String,
    val paymentTermLabel: String,
    val sameDayLabel: String,
    val termsLabel: String,
    val noPaymentTermsAvailable: String
)

data class CustomerStrings(
    val title: String,
    val selectPaymentMode: String,
    val emptyOsInvoices: String,
    val refreshCustomers: String,
    val emptyCustomers: String,
    val emptySearchCustomers: String,
    val searchPlaceholder: String,
    val searchIconDescription: String,
    val clearSearchDescription: String,
    val allLabel: String,
    val pendingFilterLabel: String,
    val noPendingFilterLabel: String,
    val overdueLabel: String,
    val activeLabel: String,
    val pendingLabel: String,
    val availableLabel: String,
    val limitLabel: String,
    val outstandingSummaryTitle: String,
    val outstandingSummaryInvoicesLabel: String,
    val outstandingSummaryAmountLabel: String,
    val outstandingInvoicesTitle: String,
    val createQuotationLabel: String,
    val createSalesOrderLabel: String,
    val createDeliveryNoteLabel: String,
    val createInvoiceLabel: String,
    val selectCustomerToViewInvoices: String,
    val noOutstandingInvoices: String,
    val postedLabel: String,
    val outstandingLabel: String,
    val registerPaymentTitle: String,
    val invoiceIdLabel: String,
    val paymentModeLabel: String,
    val amountLabel: String,
    val processing: String,
    val registerPaymentButton: String,
    val moreActions: String,
    val balance: String,
    val outOfStock: String,
    val inStock: String,
    val baseCurrency: String
)

data class InventoryStrings(
    val loadInventoryError: String,
    val loadMoreError: String,
    val retry: String,
    val productAvailableLabel: String,
    val productCategoryLabel: String,
    val productUomLabel: String,
    val productCodeLabel: String,
    val productOutOfStock: String,
    val errorPrefix: String,
    val emptySearchMessage: String
)

data class SettingsStrings(
    val title: String,
    val generalTitle: String,
    val companyLabel: String,
    val posProfileLabel: String,
    val warehouseLabel: String,
    val priceListLabel: String,
    val operationTitle: String,
    val taxesIncludedLabel: String,
    val offlineModeLabel: String,
    val hardwareTitle: String,
    val printerEnabledLabel: String,
    val cashDrawerEnabledLabel: String,
    val syncTitle: String,
    val syncStatusLabel: String,
    val syncLastLabel: String,
    val syncNowButton: String,
    val autoSyncLabel: String,
    val syncOnStartupLabel: String,
    val wifiOnlyLabel: String,
    val lastSyncNever: String,
    val syncStatusIdle: String,
    val syncStatusSuccess: String,
    val syncStatusError: String,
    val syncStatusSyncing: String,
    val languageTitle: String,
    val languageLabel: String,
    val languageSpanish: String,
    val languageEnglish: String,
    val languageInstantHint: String
)

data class SalesFlowStrings(
    val customerLabel: String,
    val sourceLabel: String
)

data class NavigationStrings(
    val home: String,
    val customer: String,
    val invoice: String,
    val billing: String,
    val inventory: String,
    val reconciliation: String
)

data class ReconciliationStrings(
    val title: String,
    val subtitle: String,
    val summaryTitle: String,
    val totalSessionsLabel: String,
    val pendingSyncLabel: String,
    val latestCloseLabel: String,
    val checklistTitle: String,
    val checklistStepOne: String,
    val checklistStepTwo: String,
    val checklistStepThree: String,
    val sessionsTitle: String,
    val loadingLabel: String,
    val emptyTitle: String,
    val emptyMessage: String,
    val confirmCloseTitle: String,
    val confirmCloseBody: String,
    val confirmCloseButton: String,
    val closeInProgressLabel: String,
    val closeSuccessMessage: String,
    val statusSynced: String,
    val statusPending: String,
    val closingAmountLabel: String,
    val periodLabel: String,
    val openingLabel: String,
    val entryIdLabel: String,
    val openingAmountTitle: String,
    val openingBreakdownLabel: String,
    val cashierLabel: String,
    val shiftLabel: String,
    val dateLabel: String,
    val systemSummaryTitle: String,
    val expectedTotalLabel: String,
    val salesLabel: String,
    val paymentsLabel: String,
    val creditPartialLabel: String,
    val creditPendingLabel: String,
    val expensesLabel: String,
    val invoicesLabel: String,
    val expectedByCurrencyLabel: String,
    val paymentsByCurrencyLabel: String,
    val paymentMethodsTitle: String,
    val paymentMethodsSubtitle: String,
    val expectedLabel: String,
    val countedLabel: String,
    val differenceLabel: String,
    val differenceTitle: String,
    val unassignedModeLabel: String,
    val cashCountTitle: String,
    val cashCountSubtitle: String,
    val billsLabel: String,
    val coinsLabel: String,
    val totalCountedLabel: String,
    val notesTitle: String,
    val notesPlaceholder: String,
    val saveDraftLabel: String,
    val closeCashboxLabel: String,
    val closeWithDifferenceLabel: String,
    val differenceBalancedTitle: String,
    val differenceBalancedBody: String,
    val differenceShortTitle: String,
    val differenceOverTitle: String,
    val differenceShortLabel: String,
    val differenceOverLabel: String,
    val differencePerfectBadge: String,
    val differenceAttentionBadge: String,
    val differenceReviewBadge: String,
    val onlineLabel: String
)

object AppStringsFactory {
    fun forLanguage(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.Spanish -> spanish()
            AppLanguage.English -> english()
        }
    }

    private fun spanish() = AppStrings(
        billing = BillingStrings(
            newInvoiceTitle = "Nueva factura",
            emptyCartSnackbar = "No hay productos en el carrito",
            returnButton = "Volver",
            customerSectionTitle = "Cliente",
            cartSectionTitle = "Carrito",
            creditTermsSectionTitle = "Términos de crédito",
            finalizeSale = "Finalizar venta",
            sourceDocumentLinked = "Documento de origen vinculado",
            linkSourceDocument = "Vincular documento de origen",
            linkSourceDocumentTitle = "Vincular documento de origen",
            sourceTypeLabel = "Tipo de origen",
            sourceTypeQuotation = "Cotización",
            sourceTypeSalesOrder = "Orden de venta",
            sourceTypeDeliveryNote = "Nota de entrega",
            sourceTypeCustomer = "Cliente",
            selectCustomerForDocuments = "Selecciona un cliente para cargar documentos.",
            filterByIdOrStatus = "Filtrar por ID o estado",
            noDocumentsFound = "No se encontraron documentos.",
            dateLabel = "Fecha",
            statusLabel = "Estado",
            unknownStatus = "Desconocido",
            searchCustomerLabel = "Buscar o seleccionar",
            searchCustomerPlaceholder = "Nombre, código, teléfono...",
            productSectionTitle = "Producto",
            productSearchLabel = "Buscar por nombre o código",
            productSearchPlaceholder = "Nombre, código...",
            productCodeLabel = "Cód.",
            productPriceLabel = "Precio",
            productAvailableLabel = "Disponibilidad",
            cartEmptyTitle = "Carrito vacío",
            cartItemsLabel = "Artículos",
            quantityLabelShort = "Cant.",
            decreaseQuantityDescription = "Disminuir cantidad",
            increaseQuantityDescription = "Aumentar cantidad",
            removeItemDescription = "Eliminar",
            totalsPaymentsTitle = "Totales + pagos",
            totalsDiscountsShippingTitle = "Totales + descuentos + envío",
            subtotalLabel = "Subtotal",
            taxesLabel = "Impuestos",
            discountLabel = "Descuento",
            shippingLabel = "Envío",
            totalLabel = "Total",
            paymentsTitle = "Pagos",
            paymentsDisabledCreditSale = "Pagos deshabilitados para ventas a crédito.",
            paymentsEmpty = "Sin pagos registrados",
            amountLabel = "Monto",
            baseLabel = "Base",
            rateLabel = "Tasa",
            referenceLabel = "Referencia",
            removePaymentLineDescription = "Eliminar línea de pago",
            partialPaymentHint = "Pago parcial (opcional). El restante quedará como saldo a crédito.",
            paymentModeLabel = "Modo de pago",
            paymentModePlaceholder = "Selecciona método de pago",
            invoiceBaseCurrencyLabel = "Moneda base de factura",
            referenceNumberLabel = "Número de referencia",
            referenceRequiredHint = "Requerido para pagos con",
            addPayment = "Agregar pago",
            removePayment = "Eliminar",
            paidBaseLabel = "Pagado (base)",
            balanceDueLabel = "Balance pendiente",
            changeLabel = "Cambio",
            discountSectionTitle = "Descuento",
            discountTypeCode = "Código",
            discountTypePercent = "Porcentaje",
            discountTypeAmount = "Monto",
            discountCodeLabel = "Código de descuento",
            discountCodePlaceholder = "Ingresa el código de descuento",
            discountPercentLabel = "Porcentaje (%)",
            discountAmountLabel = "Monto",
            shippingSectionTitle = "Envío",
            deliveryChargePlaceholder = "Selecciona cargo de envío",
            deliveryChargeLabel = "Cargo de envío",
            noShippingOption = "Sin envío",
            discountHint = "Se aplicará el descuento manual o código según corresponda.",
            creditSaleLabel = "Venta a crédito",
            paymentTermsLabel = "Condiciones de pago",
            paymentTermPlaceholder = "Selecciona la condición de pago",
            paymentTermLabel = "Condición de pago",
            sameDayLabel = "Mismo día",
            termsLabel = "Términos",
            noPaymentTermsAvailable = "No hay términos de pago disponibles. Las ventas a crédito están deshabilitadas."
        ),
        customer = CustomerStrings(
            title = "Clientes",
            refreshCustomers = "Actualizar clientes",
            emptyCustomers = "No hay clientes disponibles.",
            emptySearchCustomers = "No se encontraron clientes que coincidan con tu búsqueda.",
            searchPlaceholder = "Buscar cliente por nombre o teléfono...",
            searchIconDescription = "Icono de búsqueda",
            clearSearchDescription = "Borrar búsqueda",
            allLabel = "Todos",
            pendingFilterLabel = "Pendientes",
            noPendingFilterLabel = "Sin pendientes",
            overdueLabel = "Vencido",
            pendingLabel = "Pendientes",
            availableLabel = "Disponible",
            limitLabel = "Límite",
            outstandingSummaryTitle = "Resumen de pendientes",
            outstandingSummaryInvoicesLabel = "Fac. pendientes",
            outstandingSummaryAmountLabel = "Monto pendiente",
            outstandingInvoicesTitle = "Facturas pendientes",
            createQuotationLabel = "Crear cotización",
            createSalesOrderLabel = "Crear orden de venta",
            createDeliveryNoteLabel = "Crear nota de entrega",
            createInvoiceLabel = "Crear factura",
            selectCustomerToViewInvoices = "Selecciona un cliente para ver facturas pendientes.",
            noOutstandingInvoices = "No hay facturas pendientes para este cliente.",
            postedLabel = "Emitida",
            outstandingLabel = "Pendiente",
            registerPaymentTitle = "Registrar pago",
            invoiceIdLabel = "ID de factura",
            paymentModeLabel = "Modo de pago",
            amountLabel = "Monto",
            processing = "Procesando...",
            registerPaymentButton = "Registrar pago",
            moreActions = "Más acciones",
            balance = "Balance",
            activeLabel = "Activo",
            outOfStock = "Fuera de Stock",
            inStock = "En Stock",
            baseCurrency = "Moneda principal",
            emptyOsInvoices = "No hay facturas pendientes.",
            selectPaymentMode = "Selecciona un metodo de pago."
        ),
        inventory = InventoryStrings(
            loadInventoryError = "Error al cargar inventario",
            loadMoreError = "Error al cargar más artículos",
            retry = "Reintentar",
            productAvailableLabel = "Disponibilidad",
            productCategoryLabel = "Categoría",
            productUomLabel = "UoM",
            productCodeLabel = "Cod.",
            productOutOfStock = "Agotado",
            errorPrefix = "Error",
            emptySearchMessage = "No se encontró el artículo"
        ),
        settings = SettingsStrings(
            title = "Configuración POS",
            generalTitle = "General",
            companyLabel = "Empresa",
            posProfileLabel = "Perfil POS",
            warehouseLabel = "Almacén",
            priceListLabel = "Lista de precios",
            operationTitle = "Operación",
            taxesIncludedLabel = "Impuestos incluidos",
            offlineModeLabel = "Modo offline",
            hardwareTitle = "Hardware",
            printerEnabledLabel = "Impresora habilitada",
            cashDrawerEnabledLabel = "Cajón de dinero",
            syncTitle = "Sincronización",
            syncStatusLabel = "Estado",
            syncLastLabel = "Última sincronización",
            syncNowButton = "Sincronizar ahora",
            autoSyncLabel = "Sincronización automática",
            syncOnStartupLabel = "Sincronizar al iniciar",
            wifiOnlyLabel = "Solo Wi-Fi",
            lastSyncNever = "Sin sincronizar",
            syncStatusIdle = "En espera",
            syncStatusSuccess = "Sincronizado",
            syncStatusError = "Error",
            syncStatusSyncing = "Sincronizando",
            languageTitle = "Idioma",
            languageLabel = "Idioma de la aplicación",
            languageSpanish = "Español",
            languageEnglish = "English",
            languageInstantHint = "El cambio se aplica al instante."
        ),
        salesFlow = SalesFlowStrings(
            customerLabel = "Cliente",
            sourceLabel = "Origen"
        ),
        navigation = NavigationStrings(
            customer = "Cliente",
            inventory = "Inventario",
            home = "Inicio",
            billing = "Ventas",
            invoice = "Creditos",
            reconciliation = "Conciliación"
        ),
        reconciliation = ReconciliationStrings(
            title = "Cierre de caja",
            subtitle = "Verifica cierres, diferencias y sincronización.",
            summaryTitle = "Resumen de cierres",
            totalSessionsLabel = "Cierres totales",
            pendingSyncLabel = "Pendientes de sync",
            latestCloseLabel = "Último cierre",
            checklistTitle = "Checklist de conciliación",
            checklistStepOne = "Revisa los montos contados vs. registrados.",
            checklistStepTwo = "Valida diferencias y confirma el cierre.",
            checklistStepThree = "Sincroniza el cierre con ERPNext.",
            sessionsTitle = "Cierres recientes",
            loadingLabel = "Cargando cierres...",
            emptyTitle = "Sin cierres registrados",
            emptyMessage = "Cierra la caja para generar tu primera conciliación.",
            confirmCloseTitle = "Confirmar cierre de caja",
            confirmCloseBody = "Al confirmar, se registrará el cierre y quedará pendiente de sincronización.",
            confirmCloseButton = "Cerrar caja ahora",
            closeInProgressLabel = "Cerrando caja...",
            closeSuccessMessage = "Caja cerrada correctamente. Pendiente de sincronización.",
            statusSynced = "Sincronizado",
            statusPending = "Pendiente",
            closingAmountLabel = "Monto de cierre",
            periodLabel = "Periodo",
            openingLabel = "Apertura",
            entryIdLabel = "ID de cierre",
            openingAmountTitle = "Monto de apertura",
            openingBreakdownLabel = "Detalle de apertura",
            cashierLabel = "Cajero(a)",
            shiftLabel = "Turno",
            dateLabel = "Fecha",
            systemSummaryTitle = "Resumen del sistema",
            expectedTotalLabel = "Total esperado en caja",
            salesLabel = "Ventas en efectivo",
            paymentsLabel = "Pagos recibidos",
            creditPartialLabel = "Ventas crédito / pagos parciales",
            creditPendingLabel = "Pagos pendientes (crédito)",
            expensesLabel = "Gastos / retiros",
            invoicesLabel = "Facturas del turno",
            expectedByCurrencyLabel = "Efectivo esperado por moneda",
            paymentsByCurrencyLabel = "Pagos por moneda",
            paymentMethodsTitle = "Conciliación por método",
            paymentMethodsSubtitle = "Registra el conteo por cada método de pago.",
            expectedLabel = "Esperado",
            countedLabel = "Contado",
            differenceLabel = "Diferencia",
            differenceTitle = "Diferencia por moneda",
            unassignedModeLabel = "Sin método",
            cashCountTitle = "Conteo físico",
            cashCountSubtitle = "Ingresa la cantidad de billetes y monedas contados.",
            billsLabel = "Billetes",
            coinsLabel = "Monedas",
            totalCountedLabel = "Total contado",
            notesTitle = "Notas y observaciones",
            notesPlaceholder = "Ingresa observaciones sobre el cierre de caja...",
            saveDraftLabel = "Guardar borrador",
            closeCashboxLabel = "Cerrar caja",
            closeWithDifferenceLabel = "Cerrar con diferencia",
            differenceBalancedTitle = "Caja balanceada",
            differenceBalancedBody = "El monto contado coincide con el sistema.",
            differenceShortTitle = "Diferencia detectada: faltante",
            differenceOverTitle = "Diferencia detectada: sobrante",
            differenceShortLabel = "Faltante",
            differenceOverLabel = "Extra",
            differencePerfectBadge = "Perfecto",
            differenceAttentionBadge = "Atención",
            differenceReviewBadge = "Revisar",
            onlineLabel = "En línea"
        ),
        common = CommonStrings(
            back = "Atrás",
            retry = "Reintentar",
            remove = "Eliminar",
            clear = "Limpiar",
            link = "Vincular",
            apply = "Aplicar",
            processing = "Procesando...",
            collapseSection = "Colapsar sección",
            expandSection = "Expandir sección",
            imagePlaceholderDescription = "Imagen de marcador",
            errorLabel = "Error"
        )
    )

    private fun english() = AppStrings(
        billing = BillingStrings(
            newInvoiceTitle = "New invoice",
            emptyCartSnackbar = "There are no products in the cart",
            returnButton = "Back",
            customerSectionTitle = "Customer",
            cartSectionTitle = "Cart",
            creditTermsSectionTitle = "Credit terms",
            finalizeSale = "Finalize sale",
            sourceDocumentLinked = "Source document linked",
            linkSourceDocument = "Link a source document",
            linkSourceDocumentTitle = "Link source document",
            sourceTypeLabel = "Source type",
            sourceTypeQuotation = "Quotation",
            sourceTypeSalesOrder = "Sales order",
            sourceTypeDeliveryNote = "Delivery note",
            sourceTypeCustomer = "Customer",
            selectCustomerForDocuments = "Select a customer to load documents.",
            filterByIdOrStatus = "Filter by ID or status",
            noDocumentsFound = "No documents found.",
            dateLabel = "Date",
            statusLabel = "Status",
            unknownStatus = "Unknown",
            searchCustomerLabel = "Search or select",
            searchCustomerPlaceholder = "Name, code, phone...",
            productSectionTitle = "Product",
            productSearchLabel = "Search by name or code",
            productSearchPlaceholder = "Name, code...",
            productCodeLabel = "Cod.",
            productPriceLabel = "Price",
            productAvailableLabel = "Available",
            cartEmptyTitle = "Empty cart",
            cartItemsLabel = "Items",
            quantityLabelShort = "Qty",
            decreaseQuantityDescription = "Decrease quantity",
            increaseQuantityDescription = "Increase quantity",
            removeItemDescription = "Remove",
            totalsPaymentsTitle = "Totals + payments",
            totalsDiscountsShippingTitle = "Totals + discounts + shipping",
            subtotalLabel = "Subtotal",
            taxesLabel = "Taxes",
            discountLabel = "Discount",
            shippingLabel = "Shipping",
            totalLabel = "Total",
            paymentsTitle = "Payments",
            paymentsDisabledCreditSale = "Payments are disabled for credit sales.",
            paymentsEmpty = "No payments registered",
            amountLabel = "Amount",
            baseLabel = "Base",
            rateLabel = "Rate",
            referenceLabel = "Reference",
            removePaymentLineDescription = "Remove payment line",
            partialPaymentHint = "Partial payment (optional). The remaining balance stays on credit.",
            paymentModeLabel = "Payment mode",
            paymentModePlaceholder = "Select a payment method",
            invoiceBaseCurrencyLabel = "Invoice base currency",
            referenceNumberLabel = "Reference number",
            referenceRequiredHint = "Required for payments with",
            addPayment = "Add payment",
            removePayment = "Remove",
            paidBaseLabel = "Paid (base)",
            balanceDueLabel = "Balance due",
            changeLabel = "Change",
            discountSectionTitle = "Discount",
            discountTypeCode = "Code",
            discountTypePercent = "Percent",
            discountTypeAmount = "Amount",
            discountCodeLabel = "Discount code",
            discountCodePlaceholder = "Enter discount code",
            discountPercentLabel = "Percent (%)",
            discountAmountLabel = "Amount",
            shippingSectionTitle = "Shipping",
            deliveryChargePlaceholder = "Select shipping charge",
            deliveryChargeLabel = "Shipping charge",
            noShippingOption = "No shipping",
            discountHint = "The manual or code discount will apply as needed.",
            creditSaleLabel = "Credit sale",
            paymentTermsLabel = "Payment terms",
            paymentTermPlaceholder = "Select payment term",
            paymentTermLabel = "Payment term",
            sameDayLabel = "Same day",
            termsLabel = "Terms",
            noPaymentTermsAvailable = "No payment terms available. Credit sales are disabled."
        ),
        customer = CustomerStrings(
            title = "Customers",
            refreshCustomers = "Refresh customers",
            emptyCustomers = "No customers available.",
            emptySearchCustomers = "No customers match your search.",
            searchPlaceholder = "Search by name or phone...",
            searchIconDescription = "Search icon",
            clearSearchDescription = "Clear search",
            allLabel = "All",
            pendingFilterLabel = "Pending",
            noPendingFilterLabel = "No pending",
            overdueLabel = "Overdue",
            pendingLabel = "Pending",
            availableLabel = "Available",
            limitLabel = "Limit",
            outstandingSummaryTitle = "Outstanding summary",
            outstandingSummaryInvoicesLabel = "O/S invoices",
            outstandingSummaryAmountLabel = "O/S amount",
            outstandingInvoicesTitle = "O/S invoices",
            createQuotationLabel = "Create quotation",
            createSalesOrderLabel = "Create sales order",
            createDeliveryNoteLabel = "Create delivery note",
            createInvoiceLabel = "Create invoice",
            selectCustomerToViewInvoices = "Select a customer to view outstanding invoices.",
            noOutstandingInvoices = "No outstanding invoices for this customer.",
            postedLabel = "Posted",
            outstandingLabel = "Outstanding",
            registerPaymentTitle = "Register payment",
            invoiceIdLabel = "Invoice ID",
            paymentModeLabel = "Mode of payment",
            amountLabel = "Amount",
            processing = "Processing...",
            registerPaymentButton = "Register payment",
            moreActions = "More actions",
            balance = "Balance",
            activeLabel = "Active",
            outOfStock = "Out of stock",
            inStock = "In Stock",
            baseCurrency = "Base currency",
            emptyOsInvoices = "No outstanding invoices for this customer.",
            selectPaymentMode = "Select payment mode"
        ),
        inventory = InventoryStrings(
            loadInventoryError = "Unable to load inventory",
            loadMoreError = "Unable to load more items",
            retry = "Retry",
            productAvailableLabel = "Available",
            productCategoryLabel = "Category",
            productUomLabel = "UoM",
            productCodeLabel = "Cod.",
            productOutOfStock = "Out of stock",
            errorPrefix = "Error",
            emptySearchMessage = "No items found"
        ),
        settings = SettingsStrings(
            title = "POS settings",
            generalTitle = "General",
            companyLabel = "Company",
            posProfileLabel = "POS profile",
            warehouseLabel = "Warehouse",
            priceListLabel = "Price list",
            operationTitle = "Operations",
            taxesIncludedLabel = "Taxes included",
            offlineModeLabel = "Offline mode",
            hardwareTitle = "Hardware",
            printerEnabledLabel = "Printer enabled",
            cashDrawerEnabledLabel = "Cash drawer",
            syncTitle = "Synchronization",
            syncStatusLabel = "Status",
            syncLastLabel = "Last sync",
            syncNowButton = "Sync now",
            autoSyncLabel = "Auto-sync",
            syncOnStartupLabel = "Sync on startup",
            wifiOnlyLabel = "Wi-Fi only",
            lastSyncNever = "Never synced",
            syncStatusIdle = "Idle",
            syncStatusSuccess = "Synced",
            syncStatusError = "Error",
            syncStatusSyncing = "Syncing",
            languageTitle = "Language",
            languageLabel = "Application language",
            languageSpanish = "Spanish",
            languageEnglish = "English",
            languageInstantHint = "Changes apply instantly."
        ),
        salesFlow = SalesFlowStrings(
            customerLabel = "Customer",
            sourceLabel = "Source"
        ),
        navigation = NavigationStrings(
            customer = "Customer",
            inventory = "Inventory",
            invoice = "Credits",
            home = "Home",
            billing = "Billing",
            reconciliation = "Reconciliation"
        ),
        reconciliation = ReconciliationStrings(
            title = "Cash closing",
            subtitle = "Review closures, differences, and sync status.",
            summaryTitle = "Closing summary",
            totalSessionsLabel = "Total closings",
            pendingSyncLabel = "Pending sync",
            latestCloseLabel = "Latest closing",
            checklistTitle = "Reconciliation checklist",
            checklistStepOne = "Compare counted cash vs. recorded totals.",
            checklistStepTwo = "Validate differences and confirm the closing.",
            checklistStepThree = "Sync the closing with ERPNext.",
            sessionsTitle = "Recent closings",
            loadingLabel = "Loading closings...",
            emptyTitle = "No closings yet",
            emptyMessage = "Close the cashbox to create the first reconciliation.",
            confirmCloseTitle = "Confirm cashbox closing",
            confirmCloseBody = "Confirming will create the closing entry and mark it pending sync.",
            confirmCloseButton = "Close cashbox now",
            closeInProgressLabel = "Closing cashbox...",
            closeSuccessMessage = "Cashbox closed. Pending synchronization.",
            statusSynced = "Synced",
            statusPending = "Pending",
            closingAmountLabel = "Closing amount",
            periodLabel = "Period",
            openingLabel = "Opening",
            entryIdLabel = "Closing ID",
            openingAmountTitle = "Opening amount",
            openingBreakdownLabel = "Opening breakdown",
            cashierLabel = "Cashier",
            shiftLabel = "Shift",
            dateLabel = "Date",
            systemSummaryTitle = "System summary",
            expectedTotalLabel = "Expected cash total",
            salesLabel = "Cash sales",
            paymentsLabel = "Payments received",
            creditPartialLabel = "Credit sales / partial payments",
            creditPendingLabel = "Pending payments (credit)",
            expensesLabel = "Expenses / withdrawals",
            invoicesLabel = "Shift invoices",
            expectedByCurrencyLabel = "Expected cash by currency",
            paymentsByCurrencyLabel = "Payments by currency",
            paymentMethodsTitle = "Payment method reconciliation",
            paymentMethodsSubtitle = "Enter the count for each payment method.",
            expectedLabel = "Expected",
            countedLabel = "Counted",
            differenceLabel = "Difference",
            differenceTitle = "Cash difference by currency",
            unassignedModeLabel = "Unassigned",
            cashCountTitle = "Cash count",
            cashCountSubtitle = "Enter the number of bills and coins counted.",
            billsLabel = "Bills",
            coinsLabel = "Coins",
            totalCountedLabel = "Total counted",
            notesTitle = "Notes and observations",
            notesPlaceholder = "Add notes about the cash closing...",
            saveDraftLabel = "Save draft",
            closeCashboxLabel = "Close cashbox",
            closeWithDifferenceLabel = "Close with difference",
            differenceBalancedTitle = "Cashbox balanced",
            differenceBalancedBody = "Counted total matches the system.",
            differenceShortTitle = "Difference detected: shortage",
            differenceOverTitle = "Difference detected: overage",
            differenceShortLabel = "Shortage",
            differenceOverLabel = "Extra",
            differencePerfectBadge = "Perfect",
            differenceAttentionBadge = "Needs attention",
            differenceReviewBadge = "Review",
            onlineLabel = "Online"
        ),
        common = CommonStrings(
            back = "Back",
            retry = "Retry",
            remove = "Remove",
            clear = "Clear",
            link = "Link",
            apply = "Apply",
            processing = "Processing...",
            collapseSection = "Collapse section",
            expandSection = "Expand section",
            imagePlaceholderDescription = "Placeholder image",
            errorLabel = "Error"
        )
    )
}

val LocalAppStrings = staticCompositionLocalOf {
    AppStringsFactory.forLanguage(AppLanguage.Spanish)
}
